CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    email varchar(100) NOT NULL UNIQUE,
    name varchar(50) NOT NULL,
    updated_at timestamp NOT NULL,
    password varchar(255),
    provider varchar(20),
    demo_mutation_count integer DEFAULT 0 NOT NULL,
    expires_at timestamp
);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    name varchar(100) NOT NULL,
    updated_at timestamp NOT NULL,
    owner_user_id bigint,
    CONSTRAINT fk_projects_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_event_id varchar(100),
    calendar_sync_enabled boolean NOT NULL,
    created_at timestamp NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp,
    description text,
    due_at timestamp,
    start_at timestamp,
    status varchar(20) NOT NULL,
    title varchar(200) NOT NULL,
    updated_at timestamp NOT NULL,
    assignee_user_id bigint REFERENCES users(id),
    project_id bigint NOT NULL REFERENCES projects(id)
);

CREATE TABLE task_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_value text,
    before_value text,
    change_type varchar(30) NOT NULL,
    created_at timestamp NOT NULL,
    changed_by_user_id bigint NOT NULL REFERENCES users(id),
    task_id bigint NOT NULL REFERENCES tasks(id)
);

CREATE TABLE oauth_google_tokens (
    user_id bigint PRIMARY KEY,
    access_token text NOT NULL,
    created_at timestamp NOT NULL,
    expiry_at timestamp NOT NULL,
    refresh_token text NOT NULL,
    scope text NOT NULL,
    updated_at timestamp NOT NULL,
    version bigint
);

CREATE TABLE calendar_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    last_error text,
    next_retry_at timestamp,
    op_type varchar(10) NOT NULL,
    payload text NOT NULL,
    retry_count integer NOT NULL,
    status varchar(15) NOT NULL,
    task_id bigint NOT NULL,
    updated_at timestamp NOT NULL
);
CREATE INDEX idx_outbox_status_next_retry ON calendar_outbox(status, next_retry_at);
CREATE INDEX idx_outbox_task_created ON calendar_outbox(task_id, created_at);
CREATE INDEX idx_outbox_task_status_optype ON calendar_outbox(task_id, status, op_type);

CREATE TABLE task_search_embeddings (
    task_id bigint PRIMARY KEY REFERENCES tasks(id) ON DELETE CASCADE,
    source_text text NOT NULL,
    text_hash varchar(64) NOT NULL,
    embedding vector(3072) NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_task_search_embeddings_updated_at ON task_search_embeddings(updated_at);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO taskflow_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO taskflow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE taskflow_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO taskflow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE taskflow_owner IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO taskflow_app;
