global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: taskflow
    metrics_path: /actuator/prometheus
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: demo_tasks_total
        target_label: __name__
        replacement: demo_tasks_created_total
    static_configs:
      - targets: [backend:9091]
